name: Upgrades
on: [push, pull_request]
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  upgrade:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        from: ['1.7.0.6', '1.7.6.9', '1.7.6.1', '1.7.7.0', '8.0.0', '8.1.0']
        ps-versions:
          - channel: minor
          - channel: major
    runs-on: ubuntu-latest
    name: Upgrade
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Composer Install
        run: composer install
      - name: Upgrade & Rollback
        uses: ./.github/
